### ISSUE TITLE
Yet another benchmark repository

### ISSUE THREAD

**Issue by sebwolf-de** [SeisSol/Examples#10]
Hi,
are you aware of this repository, with very helpful scripts for the convergence tests: https://gitlab.lrz.de/seissol.org/benchmark?
I see there is already a convergence_elastic folder in here, can we merge these repos?

**Comment by krenzland** [comment]
Here's a fixed link: https://gitlab.lrz.de/seissol.org/benchmarks
Yes, we should merge them - but should clear out the license issues first.

**Comment by sebwolf-de** [comment]
Authors are @krenzland @uphoffc @ravil-mobile and me.

**Comment by Thomas-Ulrich** [comment]
@sebwolf-de can we close the issue?
