### ISSUE TITLE
 invalid line in namelist Output: iPlasticityMask = 0 0 0 0 0 0 1 in parameters.par file for tpv5

### ISSUE THREAD

**Issue by ThrudPrimrose** [SeisSol/Examples#31]
The parameters.par file from the examples repository does result with a runtime error. (Also the parameters.par does not contain, iOutputMaskMaterial, I am not sure if it is a necessary or an optional parameter) 

The output message with the parameters.par from the repo:

```
mpirun -n 2 ./SeSol_Release_snoarch_6_elastic parameters.par 
Thu Nov 04 13:09:55, Info:  Welcome to SeisSol 
Thu Nov 04 13:09:55, Info:  Copyright (c) 2012-2021, SeisSol Group 
Thu Nov 04 13:09:55, Info:  Built on: Nov  4 2021 12:58:45 
Thu Nov 04 13:09:55, Info:  Version: 202103_Sumatra-243-g6bf3b81b (modified) 
Thu Nov 04 13:09:55, Info:  Running on: primrose 
Thu Nov 04 13:09:55, Info:  Using OMP with #threads/rank: 2 
Thu Nov 04 13:09:55, Info:  OpenMP worker affinity (this process): "0---4---" 
Thu Nov 04 13:09:55, Info:  OpenMP worker affinity (this node)   : "01--45--" 
Thu Nov 04 13:09:55, Info:  Using MPI with #ranks: 2 
Thu Nov 04 13:09:55, Info:  Running with communication thread 
Thu Nov 04 13:09:55, Info:  Communication thread affinity: "--23--67" 
Thu Nov 04 13:09:55, Info:  The stack size ulimit is  8192 [kb]. 
Thu Nov 04 13:09:55, Warn:  Stack size of 8192 [kb] is lower than recommended minimum of 2097152 [kb]. You can increase the stack size by running the command: ulimit -Ss unlimited. 
Rank:        0 | Info    | <--------------------------------------------------------->
Rank:        0 | Info    | <                SeisSol MPI initialization               >
Rank:        0 | Info    | <--------------------------------------------------------->
Rank:        0 | Info    |  Double precision used for real.
Rank:        0 | Info    | <--------------------------------------------------------->
 INFORMATION: The assumed unit number is           6 for stdout and           0 for stderr.
              If no information follows, please change the value.
Rank:        0 | Info    | <--------------------------------------------------------->
Rank:        0 | Info    | <     Start ini_SeisSol ...                               >
Rank:        0 | Info    | <--------------------------------------------------------->
Rank:        0 | Info    | <  Parameters read from file: parameters.par              >
Rank:        0 | Info    | <                                                         >
Rank:        0 | Info    | No plasticity assumed. 
Rank:        0 | Info    | No attenuation assumed. 
Rank:        0 | Info    | No adjoint wavefield generated. 
Rank:        0 | Info    | Isotropic material is assumed. 
Rank:        0 | Info    | GPwise initialization. 
Rank:        0 | Info    | RF output in extra files on
Rank:        0 | Info    | Number of pickPoints =            9
Rank:        0 | Info    |  Pickpoints read from tpv5_faultreceivers.dat
Rank:        1 | Error   | invalid line in namelist Output: iPlasticityMask = 0 0 0 0 0 0 1
Rank:        0 | Info    | Read a PUML mesh file
Rank:        0 | Warning | Ignoring min space order from parameter file, using           6
Rank:        0 | Error   | invalid line in namelist Output: iPlasticityMask = 0 0 0 0 0 0 1
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[45331,1],0]
  Exit code:    134
--------------------------------------------------------------------------
```
When the line is commented out, I do not have any runtime error.

**Comment by Thomas-Ulrich** [comment]
Hi, you need to pull the latest SeisSol and recompile it.
The iPlasticityMask has been introduce with this PR https://github.com/SeisSol/SeisSol/pull/346

**Comment by ThrudPrimrose** [comment]
ineed was the case.

**Comment by jwjeremy** [comment]
Hi, I am trying to run this example in the seissol docker and also resulted in the same issue, may I ask how to recompile the latest seissol in docker?

**Comment by krenzland** [comment]
In principle you should be able to clone
https://github.com/SeisSol/Training
and run "docker build . " in the root directory of the repository.
to compile a new version of the image.
Unfortunately I do not have the necessary rights to push a version to Dockerhub.

**Comment by jwjeremy** [comment]
I see! Thank you!

**Comment by krenzland** [comment]
Let us know if this works. If not, we can update the Docker container.
@uphoffc Am I correct that currently, you're the only one with the necessary rights for this?

**Comment by jwjeremy** [comment]
I have encountered an error during building the docker at the step of setting up SCOREC. The error msg is as follow

> executor failed running [/bin/sh -c git clone https://github.com/SCOREC/core.git     && cd core     && mkdir build && cd build     && cmake .. -DCMAKE_INSTALL_PREFIX=/home/tools -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=Release -DSCOREC_CXX_FLAGS="-Wno-error=array-bounds"     && make -j4 && make install]: exit code: 2

> #18 96.99 CMake Error at test/cmake_install.cmake:1692 (file):
> #18 96.99   file INSTALL cannot find "/tmp/core/pumi-meshes/pipe/pipe.dmg": No such
> #18 96.99   file or directory.
> #18 96.99 Call Stack (most recent call first):
> #18 96.99   cmake_install.cmake:92 (include)

**Comment by Thomas-Ulrich** [comment]
Hi, I also got this error yesterday when compiling pumgen. Core repository now has a submodule which should be initialized. We need to update the docker file. 

Le 5 novembre 2021 18:09:32 GMT+01:00, Jeremy Wong ***@***.***> a écrit :

**Comment by krenzland** [comment]
The core repository should be fixed to a stable commit as well
