### ISSUE TITLE
TPV5: Definition of both nucleation stress and traction crashes SeisSol

### ISSUE THREAD

**Issue by mariusbohn** [SeisSol/Examples#40]
The additions to fault.yaml from commit `c6257940f72ff3adc9ff836cb253a7d67416f13f` cause SeisSol to crash after parameter initialization. I tried only TPV5 but it is to be assumed that other examples might be affected as well. Output is as follows:
`Error: Both nucleation stress (nuc_xx, nuc_yy, nuc_zz, nuc_xy, nuc_yz, nuc_xz) and nucleation traction (Tnuc_n, Tnuc_s, Tnuc_d) are defined (or are missing), but only either of them must be defined.`

**Comment by krenzland** [comment]
Closed by https://github.com/SeisSol/Examples/pull/41
